### ISSUE TITLE
undefined method `each_chunk' for "":String (NoMethodError)

### ISSUE THREAD

**Issue by gobijan** [jaigouk/gpt4all#4]
Hi I was in the process of developing my own gem but found this.

The each_chunk method seems problematic.

/Users/bijan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gpt4all-0.0.4/lib/gpt4all/conversational_ai.rb:160:in `block in write_chunks_to_file': undefined method `each_chunk' for "":String (NoMethodError)

        response.body.each_chunk do |chunk|
                     ^^^^^^^^^^^
Did you mean?  each_char
        from /Users/bijan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gpt4all-0.0.4/lib/gpt4all/conversational_ai.rb:158:in `open'
        from /Users/bijan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gpt4all-0.0.4/lib/gpt4all/conversational_ai.rb:158:in `write_chunks_to_file'
        from /Users/bijan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gpt4all-0.0.4/lib/gpt4all/conversational_ai.rb:154:in `download_with_progress_bar'
        from /Users/bijan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gpt4all-0.0.4/lib/gpt4all/conversational_ai.rb:126:in `download_file'
        from /Users/bijan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gpt4all-0.0.4/lib/gpt4all/conversational_ai.rb:96:in `download_executable'
        from /Users/bijan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/gpt4all-0.0.4/lib/gpt4all/conversational_ai.rb:41:in `prepare_resources'
        from app.rb:4:in `<main>'

**Comment by jaigouk** [comment]
let me check

**Comment by jaigouk** [comment]
I hope that fixed the issue. pushed v0.0.5
